<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="MS-20170914WAMZ" ignored="3" name="Test(failed)" tests="2" failures="2" timestamp="07 十二月 2017 06:32:44 GMT" time="0.0" errors="0">
  <testcase name="test05" time="0.0" classname="testngdemo2.ReRunTestFailed">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testngdemo2.ReRunTestFailed.test05(ReRunTestFailed.java:42)
	at testngdemo2.ReRunTestNG.main(ReRunTestNG.java:36)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test05 -->
  <testcase name="test03" time="0.0" classname="testngdemo2.ReRunTestFailed">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
	at testngdemo2.ReRunTestFailed.test03(ReRunTestFailed.java:31)
	at testngdemo2.ReRunTestNG.main(ReRunTestNG.java:36)
... Removed 26 stack frames]]>
    </failure>
  </testcase> <!-- test03 -->
  <testcase name="test02" time="0.0" classname="testngdemo2.ReRunTestFailed">
    <ignored/>
  </testcase> <!-- test02 -->
  <testcase name="test01" time="0.0" classname="testngdemo2.ReRunTestFailed">
    <ignored/>
  </testcase> <!-- test01 -->
  <testcase name="test04" time="0.0" classname="testngdemo2.ReRunTestFailed">
    <ignored/>
  </testcase> <!-- test04 -->
</testsuite> <!-- Test(failed) -->
